name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.target.runs-on }}
    strategy:
      matrix:
        target:
          - name: linux-amd64
            runs-on: ubuntu-latest
          - name: linux-aarch64
            runs-on: ubuntu-latest
          - name: darwin-amd64
            runs-on: macos-13
          - name: darwin-arm64
            runs-on: macos-14
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Prepare for build
        run: |
          bazel/setup-ci.sh
          mkdir -p editors/code/dist
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
      - name: Build
        run: bazel build -c opt ${{ matrix.target.name == 'linux-aarch64' && '--platforms @zig_sdk//platform:linux_arm64' || '' }} //:sty
      - uses: actions/upload-artifact@v4
        with:
          name: sty-${{ matrix.target.name }}
          path: bazel-bin/crates/starpls/sty

  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare for build
        run: |
          echo 'import %workspace%/bazel/remote-cache.bazelrc' >>.bazelrc
          echo "build --remote_header=x-buildbuddy-api-key=$BUILDBUDDY_API_KEY" >>.bazelrc
          echo "startup --output_user_root=C:/b" >>.bazelrc
          echo "startup --windows_enable_symlinks" >>.bazelrc
          mkdir -p editors/code/dist
        shell: bash
        env:
          BUILDBUDDY_API_KEY: ${{ secrets.BUILDBUDDY_API_KEY }}
      - name: Build
        run: bazel build -c opt //:sty
      - uses: actions/upload-artifact@v4
        with:
          name: sty-windows-amd64
          path: bazel-bin/crates/starpls/sty.exe

  release:
    name: Release
    needs: [build, build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: sty-*
      - name: Prepare release artifacts
        run: |
          mkdir -p release
          mv artifacts/sty-linux-aarch64/sty release/sty-linux-aarch64
          mv artifacts/sty-linux-amd64/sty release/sty-linux-amd64
          mv artifacts/sty-darwin-amd64/sty release/sty-darwin-amd64
          mv artifacts/sty-darwin-arm64/sty release/sty-darwin-arm64
          mv artifacts/sty-windows-amd64/sty.exe release/sty-windows-amd64.exe
          chmod +x release/sty-*

          # Also create archives for usage by installation methods like Homebrew.
          # Eventually, we'll remove the non-zipped binaries above.
          cd release
          cp sty-linux-aarch64 sty && tar -czvf sty-linux-aarch64.tar.gz sty && rm sty
          cp sty-linux-amd64 sty && tar -czvf sty-linux-amd64.tar.gz sty && rm sty
          cp sty-darwin-amd64 sty && tar -czvf sty-darwin-amd64.tar.gz sty && rm sty
          cp sty-darwin-arm64 sty && tar -czvf sty-darwin-arm64.tar.gz sty && rm sty
          cp sty-windows-amd64.exe sty.exe && zip sty-windows-amd64.zip sty.exe && rm sty.exe
      - name: Show release artifacts
        run: find release
      - name: Create release
        run: |
          gh release create ${{ github.ref_name }} release/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
